### PR TITLE
Introducing JavaScript Extension

### PR DESCRIPTION
**Pull request by MRHMisu**
This **pull request** introduces JavaScript Extension for Siamese.  The extension has been developed following the **Siamese Language Extension Manual** provided by @tsuiwwwayne. 

Four Interfaces are implemented with some additional classes.  Implemented Interfaces for JavaScript can be found under the package **crest.siamese.language.javascript**

- JSNormalizer.java
- JSTokenizer.java
- JSMethodParser.java 
- JSNormalizerMode.java

**Additional Classes:** 
- JSParseTreeListener.java
- Builder.java
- ErrorListenerTest.java

**Two supportive Classes** are required to store inside the **crest.siamese.language.javascript.antlr4**.  These classes are provided with [ANTLR4 JavaScript Grammar ](https://github.com/antlr/grammars-v4/tree/master/javascript/javascript/Java)  They will not be generated by ANTLR4; instead, the generated **JavaScriptLexer** and **JavaScriptParser** are inherited from these classes. 

- JavaScriptLexerBase.java
- JavaScriptParserBase.java

Apart from this,  Siamese now can take multiple file extension as input, for example, in the config.properties file:
- **extension=js, jsx**

For all newly added classes, **38 unit test cases** are added. The test suit has achieved almost **100% Line Coverage.**

Feel free, to ask any question regarding the JavaScript extension.

### CODE REVIEW

**Comment by MRHMisu** [comment]
@cragkhit  Could you please review and approve the pull request?

**Review by cragkhit — CHANGES_REQUESTED** [review]
Hi @MRHMisu. This looks really good! I have only one request. Can you revert the change in the original `config.properties` file to the Java version so that I can keep it for using with Java? I have seen that you have the Javascript config.properties already in the `configs/toxic-code-analysis/javascript-study/config.properties`

**Comment by MRHMisu** [comment]
@cragkhit  Thanks for your feedback. The **config.properties** has been reverted to **Java** configuration.

**Review by cragkhit — APPROVED** [review]
Great. It's approved and now merged.

**Pull request merged**
